# SPDX-FileCopyrightText: 2026 Axle Duggan (axlecoffee) <contact@axle.coffee>
#
# SPDX-License-Identifier: CC0-1.0

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

mod.id=coffeeproxy
mod.name=CoffeeProxy
mod.version=1.2.1
mod.group=coffee.axle.proxy
mod.author=axlecoffee
mod.namespace=coffeeproxy
mod.display_name=CoffeeProxy
mod.description=Allows you to connect to servers through a SOCKS5 or HTTPS proxy
mod.discord=
mod.license=AGPL-3.0-or-later
mod.github=axlecoffee/coffeeproxy

client.user=
client.uuid=
client.modrinth_profiles_dir=

publish.modrinth=
publish.curseforge=
publish.maven_url=
publish.use_snapshot_maven=false

deps.minecraft=[VERSIONED]
deps.fapi=[VERSIONED]
deps.yarn_build=[VERSIONED]
deps.modmenu=[VERSIONED]
mod.mc_dep=[VERSIONED]
mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]
